[package]
name = "alohomora"
version = "0.1.0"
authors = ["authors go here"]
edition = "2018"

[lib]
name = "alohomora"
path = "src/lib.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
