use alohomora::pcr::{PrivacyCriticalRegion, Signature};
use crate::second::child; 

mod second;
mod third; 
fn main() {
    let _pcr = PrivacyCriticalRegion::new(|x: u8| { x + child(x) },
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUQzcm51QWVyUWg4dm1uV3doYytHcTBMR05UK2s2eHdwczZ6OUtNYjFiay9ueUhWSXYwa1krMUEwbXhzbXdldWoKNGdzYUtyUjY1L0g5ajFLLzZVTkQwTQotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}, 
        Signature {username: "corinnt", 
            signature: "LS0tLS1CRUdJTiBTU0ggU0lHTkFUVVJFLS0tLS0KVTFOSVUwbEhBQUFBQVFBQUFETUFBQUFMYzNOb0xXVmtNalUxTVRrQUFBQWd6dGJjeE9zVzlOL09Fd2c3Y3BKZ3dUQnFMNgpGazI2ZVB2Rm1ZaXpRRjM1VUFBQUFFWm1sc1pRQUFBQUFBQUFBR2MyaGhOVEV5QUFBQVV3QUFBQXR6YzJndFpXUXlOVFV4Ck9RQUFBRUQzcm51QWVyUWg4dm1uV3doYytHcTBMR05UK2s2eHdwczZ6OUtNYjFiay9ueUhWSXYwa1krMUEwbXhzbXdldWoKNGdzYUtyUjY1L0g5ajFLLzZVTkQwTQotLS0tLUVORCBTU0ggU0lHTkFUVVJFLS0tLS0K"}); 
}
